//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helpmate.Facades.LotteryWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LotteryWebService.LotteryWebServiceSoap")]
    public interface LotteryWebServiceSoap {
        
        // CODEGEN: 消息 QueryNextLotteryWithSameNumberRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryNextLotteryWithSameNumber", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Helpmate.Facades.LotteryWebService.QueryNextLotteryWithSameNumberResponse QueryNextLotteryWithSameNumber(Helpmate.Facades.LotteryWebService.QueryNextLotteryWithSameNumberRequest request);
        
        // CODEGEN: 消息 QueryLotteryByHourStepRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryLotteryByHourStep", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Helpmate.Facades.LotteryWebService.QueryLotteryByHourStepResponse QueryLotteryByHourStep(Helpmate.Facades.LotteryWebService.QueryLotteryByHourStepRequest request);
        
        // CODEGEN: 消息 QueryLotteryByDayRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryLotteryByDay", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Helpmate.Facades.LotteryWebService.QueryLotteryByDayResponse QueryLotteryByDay(Helpmate.Facades.LotteryWebService.QueryLotteryByDayRequest request);
        
        // CODEGEN: 消息 QueryLotteryByTwentyRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryLotteryByTwenty", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Helpmate.Facades.LotteryWebService.QueryLotteryByTwentyResponse QueryLotteryByTwenty(Helpmate.Facades.LotteryWebService.QueryLotteryByTwentyRequest request);
        
        // CODEGEN: 消息 QueryCurrentLotteryRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryCurrentLottery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Helpmate.Facades.LotteryWebService.QueryCurrentLotteryResponse QueryCurrentLottery(Helpmate.Facades.LotteryWebService.QueryCurrentLotteryRequest request);
        
        // CODEGEN: 消息 QueryRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Query", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Helpmate.Facades.LotteryWebService.QueryResponse Query(Helpmate.Facades.LotteryWebService.QueryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Login(string userName, string psw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Register", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Register();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegisterAndLogin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string RegisterAndLogin();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TokenHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tokenField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("Token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PageListOfLottery : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int totalField;
        
        private Lottery[] listField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
                this.RaisePropertyChanged("Total");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public Lottery[] List {
            get {
                return this.listField;
            }
            set {
                this.listField = value;
                this.RaisePropertyChanged("List");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Lottery : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int periodNumField;
        
        private System.DateTime retTimeField;
        
        private int siteSysNoField;
        
        private int retOddNumField;
        
        private int retNumField;
        
        private string retMidNumField;
        
        private string collectRetField;
        
        private System.DateTime collectTimeField;
        
        private int statusField;
        
        private LotteryType typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int PeriodNum {
            get {
                return this.periodNumField;
            }
            set {
                this.periodNumField = value;
                this.RaisePropertyChanged("PeriodNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime RetTime {
            get {
                return this.retTimeField;
            }
            set {
                this.retTimeField = value;
                this.RaisePropertyChanged("RetTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int SiteSysNo {
            get {
                return this.siteSysNoField;
            }
            set {
                this.siteSysNoField = value;
                this.RaisePropertyChanged("SiteSysNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int RetOddNum {
            get {
                return this.retOddNumField;
            }
            set {
                this.retOddNumField = value;
                this.RaisePropertyChanged("RetOddNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int RetNum {
            get {
                return this.retNumField;
            }
            set {
                this.retNumField = value;
                this.RaisePropertyChanged("RetNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string RetMidNum {
            get {
                return this.retMidNumField;
            }
            set {
                this.retMidNumField = value;
                this.RaisePropertyChanged("RetMidNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string CollectRet {
            get {
                return this.collectRetField;
            }
            set {
                this.collectRetField = value;
                this.RaisePropertyChanged("CollectRet");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public System.DateTime CollectTime {
            get {
                return this.collectTimeField;
            }
            set {
                this.collectTimeField = value;
                this.RaisePropertyChanged("CollectTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public LotteryType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LotteryType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int retNumField;
        
        private string bigOrSmallField;
        
        private string middleOrSideField;
        
        private string oddOrDualField;
        
        private string mantissaBigOrSmallField;
        
        private string threeRemainderField;
        
        private string fourRemainderField;
        
        private string fiveRemainderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int RetNum {
            get {
                return this.retNumField;
            }
            set {
                this.retNumField = value;
                this.RaisePropertyChanged("RetNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string BigOrSmall {
            get {
                return this.bigOrSmallField;
            }
            set {
                this.bigOrSmallField = value;
                this.RaisePropertyChanged("BigOrSmall");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string MiddleOrSide {
            get {
                return this.middleOrSideField;
            }
            set {
                this.middleOrSideField = value;
                this.RaisePropertyChanged("MiddleOrSide");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string OddOrDual {
            get {
                return this.oddOrDualField;
            }
            set {
                this.oddOrDualField = value;
                this.RaisePropertyChanged("OddOrDual");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string MantissaBigOrSmall {
            get {
                return this.mantissaBigOrSmallField;
            }
            set {
                this.mantissaBigOrSmallField = value;
                this.RaisePropertyChanged("MantissaBigOrSmall");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ThreeRemainder {
            get {
                return this.threeRemainderField;
            }
            set {
                this.threeRemainderField = value;
                this.RaisePropertyChanged("ThreeRemainder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string FourRemainder {
            get {
                return this.fourRemainderField;
            }
            set {
                this.fourRemainderField = value;
                this.RaisePropertyChanged("FourRemainder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string FiveRemainder {
            get {
                return this.fiveRemainderField;
            }
            set {
                this.fiveRemainderField = value;
                this.RaisePropertyChanged("FiveRemainder");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ResultRMOfPageListOfLottery : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool successField;
        
        private string messageField;
        
        private PageListOfLottery dataField;
        
        private int codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("Success");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public PageListOfLottery Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("Data");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LotteryFilter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int pageIndexField;
        
        private int pageSizeField;
        
        private System.Nullable<System.DateTime> fromField;
        
        private System.Nullable<System.DateTime> toField;
        
        private string siteNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int PageIndex {
            get {
                return this.pageIndexField;
            }
            set {
                this.pageIndexField = value;
                this.RaisePropertyChanged("PageIndex");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int PageSize {
            get {
                return this.pageSizeField;
            }
            set {
                this.pageSizeField = value;
                this.RaisePropertyChanged("PageSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<System.DateTime> From {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
                this.RaisePropertyChanged("From");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<System.DateTime> To {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
                this.RaisePropertyChanged("To");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string SiteName {
            get {
                return this.siteNameField;
            }
            set {
                this.siteNameField = value;
                this.RaisePropertyChanged("SiteName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ResultRMOfLottery : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool successField;
        
        private string messageField;
        
        private Lottery dataField;
        
        private int codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("Success");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Lottery Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("Data");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LotteryByTwentyPeriodRM : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Lottery[] lotteriesField;
        
        private int[] notAppearNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public Lottery[] Lotteries {
            get {
                return this.lotteriesField;
            }
            set {
                this.lotteriesField = value;
                this.RaisePropertyChanged("Lotteries");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public int[] NotAppearNumber {
            get {
                return this.notAppearNumberField;
            }
            set {
                this.notAppearNumberField = value;
                this.RaisePropertyChanged("NotAppearNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ResultRMOfLotteryByTwentyPeriodRM : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool successField;
        
        private string messageField;
        
        private LotteryByTwentyPeriodRM dataField;
        
        private int codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("Success");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public LotteryByTwentyPeriodRM Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("Data");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryNextLotteryWithSameNumber", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class QueryNextLotteryWithSameNumberRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Helpmate.Facades.LotteryWebService.TokenHeader TokenHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int number;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string siteName;
        
        public QueryNextLotteryWithSameNumberRequest() {
        }
        
        public QueryNextLotteryWithSameNumberRequest(Helpmate.Facades.LotteryWebService.TokenHeader TokenHeader, int number, string siteName) {
            this.TokenHeader = TokenHeader;
            this.number = number;
            this.siteName = siteName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryNextLotteryWithSameNumberResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class QueryNextLotteryWithSameNumberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Helpmate.Facades.LotteryWebService.ResultRMOfLotteryByTwentyPeriodRM QueryNextLotteryWithSameNumberResult;
        
        public QueryNextLotteryWithSameNumberResponse() {
        }
        
        public QueryNextLotteryWithSameNumberResponse(Helpmate.Facades.LotteryWebService.ResultRMOfLotteryByTwentyPeriodRM QueryNextLotteryWithSameNumberResult) {
            this.QueryNextLotteryWithSameNumberResult = QueryNextLotteryWithSameNumberResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryLotteryByHourStep", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class QueryLotteryByHourStepRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Helpmate.Facades.LotteryWebService.TokenHeader TokenHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.DateTime time;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string siteName;
        
        public QueryLotteryByHourStepRequest() {
        }
        
        public QueryLotteryByHourStepRequest(Helpmate.Facades.LotteryWebService.TokenHeader TokenHeader, System.DateTime time, string siteName) {
            this.TokenHeader = TokenHeader;
            this.time = time;
            this.siteName = siteName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryLotteryByHourStepResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class QueryLotteryByHourStepResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Helpmate.Facades.LotteryWebService.ResultRMOfLotteryByTwentyPeriodRM QueryLotteryByHourStepResult;
        
        public QueryLotteryByHourStepResponse() {
        }
        
        public QueryLotteryByHourStepResponse(Helpmate.Facades.LotteryWebService.ResultRMOfLotteryByTwentyPeriodRM QueryLotteryByHourStepResult) {
            this.QueryLotteryByHourStepResult = QueryLotteryByHourStepResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryLotteryByDay", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class QueryLotteryByDayRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Helpmate.Facades.LotteryWebService.TokenHeader TokenHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.DateTime time;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string siteName;
        
        public QueryLotteryByDayRequest() {
        }
        
        public QueryLotteryByDayRequest(Helpmate.Facades.LotteryWebService.TokenHeader TokenHeader, System.DateTime time, string siteName) {
            this.TokenHeader = TokenHeader;
            this.time = time;
            this.siteName = siteName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryLotteryByDayResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class QueryLotteryByDayResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Helpmate.Facades.LotteryWebService.ResultRMOfLotteryByTwentyPeriodRM QueryLotteryByDayResult;
        
        public QueryLotteryByDayResponse() {
        }
        
        public QueryLotteryByDayResponse(Helpmate.Facades.LotteryWebService.ResultRMOfLotteryByTwentyPeriodRM QueryLotteryByDayResult) {
            this.QueryLotteryByDayResult = QueryLotteryByDayResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryLotteryByTwenty", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class QueryLotteryByTwentyRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Helpmate.Facades.LotteryWebService.TokenHeader TokenHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string siteName;
        
        public QueryLotteryByTwentyRequest() {
        }
        
        public QueryLotteryByTwentyRequest(Helpmate.Facades.LotteryWebService.TokenHeader TokenHeader, string siteName) {
            this.TokenHeader = TokenHeader;
            this.siteName = siteName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryLotteryByTwentyResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class QueryLotteryByTwentyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Helpmate.Facades.LotteryWebService.ResultRMOfLotteryByTwentyPeriodRM QueryLotteryByTwentyResult;
        
        public QueryLotteryByTwentyResponse() {
        }
        
        public QueryLotteryByTwentyResponse(Helpmate.Facades.LotteryWebService.ResultRMOfLotteryByTwentyPeriodRM QueryLotteryByTwentyResult) {
            this.QueryLotteryByTwentyResult = QueryLotteryByTwentyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryCurrentLottery", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class QueryCurrentLotteryRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Helpmate.Facades.LotteryWebService.TokenHeader TokenHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string siteName;
        
        public QueryCurrentLotteryRequest() {
        }
        
        public QueryCurrentLotteryRequest(Helpmate.Facades.LotteryWebService.TokenHeader TokenHeader, string siteName) {
            this.TokenHeader = TokenHeader;
            this.siteName = siteName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryCurrentLotteryResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class QueryCurrentLotteryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Helpmate.Facades.LotteryWebService.ResultRMOfLottery QueryCurrentLotteryResult;
        
        public QueryCurrentLotteryResponse() {
        }
        
        public QueryCurrentLotteryResponse(Helpmate.Facades.LotteryWebService.ResultRMOfLottery QueryCurrentLotteryResult) {
            this.QueryCurrentLotteryResult = QueryCurrentLotteryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Query", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class QueryRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Helpmate.Facades.LotteryWebService.TokenHeader TokenHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Helpmate.Facades.LotteryWebService.LotteryFilter filter;
        
        public QueryRequest() {
        }
        
        public QueryRequest(Helpmate.Facades.LotteryWebService.TokenHeader TokenHeader, Helpmate.Facades.LotteryWebService.LotteryFilter filter) {
            this.TokenHeader = TokenHeader;
            this.filter = filter;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class QueryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Helpmate.Facades.LotteryWebService.ResultRMOfPageListOfLottery QueryResult;
        
        public QueryResponse() {
        }
        
        public QueryResponse(Helpmate.Facades.LotteryWebService.ResultRMOfPageListOfLottery QueryResult) {
            this.QueryResult = QueryResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LotteryWebServiceSoapChannel : Helpmate.Facades.LotteryWebService.LotteryWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LotteryWebServiceSoapClient : System.ServiceModel.ClientBase<Helpmate.Facades.LotteryWebService.LotteryWebServiceSoap>, Helpmate.Facades.LotteryWebService.LotteryWebServiceSoap {
        
        public LotteryWebServiceSoapClient() {
        }
        
        public LotteryWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LotteryWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LotteryWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LotteryWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Helpmate.Facades.LotteryWebService.QueryNextLotteryWithSameNumberResponse Helpmate.Facades.LotteryWebService.LotteryWebServiceSoap.QueryNextLotteryWithSameNumber(Helpmate.Facades.LotteryWebService.QueryNextLotteryWithSameNumberRequest request) {
            return base.Channel.QueryNextLotteryWithSameNumber(request);
        }
        
        public Helpmate.Facades.LotteryWebService.ResultRMOfLotteryByTwentyPeriodRM QueryNextLotteryWithSameNumber(Helpmate.Facades.LotteryWebService.TokenHeader TokenHeader, int number, string siteName) {
            Helpmate.Facades.LotteryWebService.QueryNextLotteryWithSameNumberRequest inValue = new Helpmate.Facades.LotteryWebService.QueryNextLotteryWithSameNumberRequest();
            inValue.TokenHeader = TokenHeader;
            inValue.number = number;
            inValue.siteName = siteName;
            Helpmate.Facades.LotteryWebService.QueryNextLotteryWithSameNumberResponse retVal = ((Helpmate.Facades.LotteryWebService.LotteryWebServiceSoap)(this)).QueryNextLotteryWithSameNumber(inValue);
            return retVal.QueryNextLotteryWithSameNumberResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Helpmate.Facades.LotteryWebService.QueryLotteryByHourStepResponse Helpmate.Facades.LotteryWebService.LotteryWebServiceSoap.QueryLotteryByHourStep(Helpmate.Facades.LotteryWebService.QueryLotteryByHourStepRequest request) {
            return base.Channel.QueryLotteryByHourStep(request);
        }
        
        public Helpmate.Facades.LotteryWebService.ResultRMOfLotteryByTwentyPeriodRM QueryLotteryByHourStep(Helpmate.Facades.LotteryWebService.TokenHeader TokenHeader, System.DateTime time, string siteName) {
            Helpmate.Facades.LotteryWebService.QueryLotteryByHourStepRequest inValue = new Helpmate.Facades.LotteryWebService.QueryLotteryByHourStepRequest();
            inValue.TokenHeader = TokenHeader;
            inValue.time = time;
            inValue.siteName = siteName;
            Helpmate.Facades.LotteryWebService.QueryLotteryByHourStepResponse retVal = ((Helpmate.Facades.LotteryWebService.LotteryWebServiceSoap)(this)).QueryLotteryByHourStep(inValue);
            return retVal.QueryLotteryByHourStepResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Helpmate.Facades.LotteryWebService.QueryLotteryByDayResponse Helpmate.Facades.LotteryWebService.LotteryWebServiceSoap.QueryLotteryByDay(Helpmate.Facades.LotteryWebService.QueryLotteryByDayRequest request) {
            return base.Channel.QueryLotteryByDay(request);
        }
        
        public Helpmate.Facades.LotteryWebService.ResultRMOfLotteryByTwentyPeriodRM QueryLotteryByDay(Helpmate.Facades.LotteryWebService.TokenHeader TokenHeader, System.DateTime time, string siteName) {
            Helpmate.Facades.LotteryWebService.QueryLotteryByDayRequest inValue = new Helpmate.Facades.LotteryWebService.QueryLotteryByDayRequest();
            inValue.TokenHeader = TokenHeader;
            inValue.time = time;
            inValue.siteName = siteName;
            Helpmate.Facades.LotteryWebService.QueryLotteryByDayResponse retVal = ((Helpmate.Facades.LotteryWebService.LotteryWebServiceSoap)(this)).QueryLotteryByDay(inValue);
            return retVal.QueryLotteryByDayResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Helpmate.Facades.LotteryWebService.QueryLotteryByTwentyResponse Helpmate.Facades.LotteryWebService.LotteryWebServiceSoap.QueryLotteryByTwenty(Helpmate.Facades.LotteryWebService.QueryLotteryByTwentyRequest request) {
            return base.Channel.QueryLotteryByTwenty(request);
        }
        
        public Helpmate.Facades.LotteryWebService.ResultRMOfLotteryByTwentyPeriodRM QueryLotteryByTwenty(Helpmate.Facades.LotteryWebService.TokenHeader TokenHeader, string siteName) {
            Helpmate.Facades.LotteryWebService.QueryLotteryByTwentyRequest inValue = new Helpmate.Facades.LotteryWebService.QueryLotteryByTwentyRequest();
            inValue.TokenHeader = TokenHeader;
            inValue.siteName = siteName;
            Helpmate.Facades.LotteryWebService.QueryLotteryByTwentyResponse retVal = ((Helpmate.Facades.LotteryWebService.LotteryWebServiceSoap)(this)).QueryLotteryByTwenty(inValue);
            return retVal.QueryLotteryByTwentyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Helpmate.Facades.LotteryWebService.QueryCurrentLotteryResponse Helpmate.Facades.LotteryWebService.LotteryWebServiceSoap.QueryCurrentLottery(Helpmate.Facades.LotteryWebService.QueryCurrentLotteryRequest request) {
            return base.Channel.QueryCurrentLottery(request);
        }
        
        public Helpmate.Facades.LotteryWebService.ResultRMOfLottery QueryCurrentLottery(Helpmate.Facades.LotteryWebService.TokenHeader TokenHeader, string siteName) {
            Helpmate.Facades.LotteryWebService.QueryCurrentLotteryRequest inValue = new Helpmate.Facades.LotteryWebService.QueryCurrentLotteryRequest();
            inValue.TokenHeader = TokenHeader;
            inValue.siteName = siteName;
            Helpmate.Facades.LotteryWebService.QueryCurrentLotteryResponse retVal = ((Helpmate.Facades.LotteryWebService.LotteryWebServiceSoap)(this)).QueryCurrentLottery(inValue);
            return retVal.QueryCurrentLotteryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Helpmate.Facades.LotteryWebService.QueryResponse Helpmate.Facades.LotteryWebService.LotteryWebServiceSoap.Query(Helpmate.Facades.LotteryWebService.QueryRequest request) {
            return base.Channel.Query(request);
        }
        
        public Helpmate.Facades.LotteryWebService.ResultRMOfPageListOfLottery Query(Helpmate.Facades.LotteryWebService.TokenHeader TokenHeader, Helpmate.Facades.LotteryWebService.LotteryFilter filter) {
            Helpmate.Facades.LotteryWebService.QueryRequest inValue = new Helpmate.Facades.LotteryWebService.QueryRequest();
            inValue.TokenHeader = TokenHeader;
            inValue.filter = filter;
            Helpmate.Facades.LotteryWebService.QueryResponse retVal = ((Helpmate.Facades.LotteryWebService.LotteryWebServiceSoap)(this)).Query(inValue);
            return retVal.QueryResult;
        }
        
        public string Login(string userName, string psw) {
            return base.Channel.Login(userName, psw);
        }
        
        public void Register() {
            base.Channel.Register();
        }
        
        public string RegisterAndLogin() {
            return base.Channel.RegisterAndLogin();
        }
    }
}
