//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTest.LotteryWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LotteryWebService.LotteryWebServiceSoap")]
    public interface LotteryWebServiceSoap {
        
        // CODEGEN: 消息 QueryLotteryByTwentyRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryLotteryByTwenty", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LotteryByTwentyPeriodRM))]
        UnitTest.LotteryWebService.QueryLotteryByTwentyResponse QueryLotteryByTwenty(UnitTest.LotteryWebService.QueryLotteryByTwentyRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TokenHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tokenField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("Token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LotteryType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int retNumField;
        
        private string bigOrSmallField;
        
        private string middleOrSideField;
        
        private string oddOrDualField;
        
        private string mantissaBigOrSmallField;
        
        private string threeRemainderField;
        
        private string fourRemainderField;
        
        private string fiveRemainderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int RetNum {
            get {
                return this.retNumField;
            }
            set {
                this.retNumField = value;
                this.RaisePropertyChanged("RetNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string BigOrSmall {
            get {
                return this.bigOrSmallField;
            }
            set {
                this.bigOrSmallField = value;
                this.RaisePropertyChanged("BigOrSmall");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string MiddleOrSide {
            get {
                return this.middleOrSideField;
            }
            set {
                this.middleOrSideField = value;
                this.RaisePropertyChanged("MiddleOrSide");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string OddOrDual {
            get {
                return this.oddOrDualField;
            }
            set {
                this.oddOrDualField = value;
                this.RaisePropertyChanged("OddOrDual");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string MantissaBigOrSmall {
            get {
                return this.mantissaBigOrSmallField;
            }
            set {
                this.mantissaBigOrSmallField = value;
                this.RaisePropertyChanged("MantissaBigOrSmall");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ThreeRemainder {
            get {
                return this.threeRemainderField;
            }
            set {
                this.threeRemainderField = value;
                this.RaisePropertyChanged("ThreeRemainder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string FourRemainder {
            get {
                return this.fourRemainderField;
            }
            set {
                this.fourRemainderField = value;
                this.RaisePropertyChanged("FourRemainder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string FiveRemainder {
            get {
                return this.fiveRemainderField;
            }
            set {
                this.fiveRemainderField = value;
                this.RaisePropertyChanged("FiveRemainder");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Lottery : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int periodNumField;
        
        private System.DateTime retTimeField;
        
        private int siteSysNoField;
        
        private int retOddNumField;
        
        private int retNumField;
        
        private string retMidNumField;
        
        private string collectRetField;
        
        private System.DateTime collectTimeField;
        
        private int statusField;
        
        private LotteryType typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int PeriodNum {
            get {
                return this.periodNumField;
            }
            set {
                this.periodNumField = value;
                this.RaisePropertyChanged("PeriodNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime RetTime {
            get {
                return this.retTimeField;
            }
            set {
                this.retTimeField = value;
                this.RaisePropertyChanged("RetTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int SiteSysNo {
            get {
                return this.siteSysNoField;
            }
            set {
                this.siteSysNoField = value;
                this.RaisePropertyChanged("SiteSysNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int RetOddNum {
            get {
                return this.retOddNumField;
            }
            set {
                this.retOddNumField = value;
                this.RaisePropertyChanged("RetOddNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int RetNum {
            get {
                return this.retNumField;
            }
            set {
                this.retNumField = value;
                this.RaisePropertyChanged("RetNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string RetMidNum {
            get {
                return this.retMidNumField;
            }
            set {
                this.retMidNumField = value;
                this.RaisePropertyChanged("RetMidNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string CollectRet {
            get {
                return this.collectRetField;
            }
            set {
                this.collectRetField = value;
                this.RaisePropertyChanged("CollectRet");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public System.DateTime CollectTime {
            get {
                return this.collectTimeField;
            }
            set {
                this.collectTimeField = value;
                this.RaisePropertyChanged("CollectTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public LotteryType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LotteryByTwentyPeriodRM : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Lottery[] lotteriesField;
        
        private int[] notAppearNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public Lottery[] Lotteries {
            get {
                return this.lotteriesField;
            }
            set {
                this.lotteriesField = value;
                this.RaisePropertyChanged("Lotteries");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public int[] NotAppearNumber {
            get {
                return this.notAppearNumberField;
            }
            set {
                this.notAppearNumberField = value;
                this.RaisePropertyChanged("NotAppearNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ResultRM : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool successField;
        
        private string messageField;
        
        private object dataField;
        
        private int codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("Success");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public object Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("Data");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryLotteryByTwenty", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class QueryLotteryByTwentyRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public UnitTest.LotteryWebService.TokenHeader TokenHeader;
        
        public QueryLotteryByTwentyRequest() {
        }
        
        public QueryLotteryByTwentyRequest(UnitTest.LotteryWebService.TokenHeader TokenHeader) {
            this.TokenHeader = TokenHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryLotteryByTwentyResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class QueryLotteryByTwentyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public UnitTest.LotteryWebService.ResultRM QueryLotteryByTwentyResult;
        
        public QueryLotteryByTwentyResponse() {
        }
        
        public QueryLotteryByTwentyResponse(UnitTest.LotteryWebService.ResultRM QueryLotteryByTwentyResult) {
            this.QueryLotteryByTwentyResult = QueryLotteryByTwentyResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LotteryWebServiceSoapChannel : UnitTest.LotteryWebService.LotteryWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LotteryWebServiceSoapClient : System.ServiceModel.ClientBase<UnitTest.LotteryWebService.LotteryWebServiceSoap>, UnitTest.LotteryWebService.LotteryWebServiceSoap {
        
        public LotteryWebServiceSoapClient() {
        }
        
        public LotteryWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LotteryWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LotteryWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LotteryWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UnitTest.LotteryWebService.QueryLotteryByTwentyResponse UnitTest.LotteryWebService.LotteryWebServiceSoap.QueryLotteryByTwenty(UnitTest.LotteryWebService.QueryLotteryByTwentyRequest request) {
            return base.Channel.QueryLotteryByTwenty(request);
        }
        
        public UnitTest.LotteryWebService.ResultRM QueryLotteryByTwenty(UnitTest.LotteryWebService.TokenHeader TokenHeader) {
            UnitTest.LotteryWebService.QueryLotteryByTwentyRequest inValue = new UnitTest.LotteryWebService.QueryLotteryByTwentyRequest();
            inValue.TokenHeader = TokenHeader;
            UnitTest.LotteryWebService.QueryLotteryByTwentyResponse retVal = ((UnitTest.LotteryWebService.LotteryWebServiceSoap)(this)).QueryLotteryByTwenty(inValue);
            return retVal.QueryLotteryByTwentyResult;
        }
    }
}
