//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTest.LotteryWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LotteryWebService.LotteryWebServiceSoap")]
    public interface LotteryWebServiceSoap {
        
        // CODEGEN: 消息 QueryNextLotteryWithSameNumberRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryNextLotteryWithSameNumber", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        UnitTest.LotteryWebService.QueryNextLotteryWithSameNumberResponse QueryNextLotteryWithSameNumber(UnitTest.LotteryWebService.QueryNextLotteryWithSameNumberRequest request);
        
        // CODEGEN: 消息 QueryLotteryByHourStepRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryLotteryByHourStep", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        UnitTest.LotteryWebService.QueryLotteryByHourStepResponse QueryLotteryByHourStep(UnitTest.LotteryWebService.QueryLotteryByHourStepRequest request);
        
        // CODEGEN: 消息 QueryLotteryByDayRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryLotteryByDay", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        UnitTest.LotteryWebService.QueryLotteryByDayResponse QueryLotteryByDay(UnitTest.LotteryWebService.QueryLotteryByDayRequest request);
        
        // CODEGEN: 消息 GetCustomeModuleRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCustomeModule", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        UnitTest.LotteryWebService.GetCustomeModuleResponse GetCustomeModule(UnitTest.LotteryWebService.GetCustomeModuleRequest request);
        
        // CODEGEN: 消息 QueryLotteryByTwentyRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryLotteryByTwenty", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        UnitTest.LotteryWebService.QueryLotteryByTwentyResponse QueryLotteryByTwenty(UnitTest.LotteryWebService.QueryLotteryByTwentyRequest request);
        
        // CODEGEN: 消息 QueryCurrentLotteryRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryCurrentLottery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        UnitTest.LotteryWebService.QueryCurrentLotteryResponse QueryCurrentLottery(UnitTest.LotteryWebService.QueryCurrentLotteryRequest request);
        
        // CODEGEN: 消息 QueryRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Query", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        UnitTest.LotteryWebService.QueryResponse Query(UnitTest.LotteryWebService.QueryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Login(string userName, string psw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Register", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Register(UnitTest.LotteryWebService.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GenerateCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GenerateCode();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryTrend", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        UnitTest.LotteryWebService.LotteryTrend QueryTrend(System.DateTime from, System.DateTime to, int pageSize, int pageIndex);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TokenHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string tokenField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("Token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PageListOfLotteryExtByBJ : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int totalField;
        
        private LotteryExtByBJ[] listField;
        
        private int pageSizeField;
        
        private int pageIndexField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
                this.RaisePropertyChanged("Total");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public LotteryExtByBJ[] List {
            get {
                return this.listField;
            }
            set {
                this.listField = value;
                this.RaisePropertyChanged("List");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int PageSize {
            get {
                return this.pageSizeField;
            }
            set {
                this.pageSizeField = value;
                this.RaisePropertyChanged("PageSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int PageIndex {
            get {
                return this.pageIndexField;
            }
            set {
                this.pageIndexField = value;
                this.RaisePropertyChanged("PageIndex");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LotteryExtByBJ : LotteryForBJ {
        
        private LotteryType typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public LotteryType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LotteryType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int retNumField;
        
        private string bigOrSmallField;
        
        private string middleOrSideField;
        
        private string oddOrDualField;
        
        private string mantissaBigOrSmallField;
        
        private string threeRemainderField;
        
        private string fourRemainderField;
        
        private string fiveRemainderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int RetNum {
            get {
                return this.retNumField;
            }
            set {
                this.retNumField = value;
                this.RaisePropertyChanged("RetNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string BigOrSmall {
            get {
                return this.bigOrSmallField;
            }
            set {
                this.bigOrSmallField = value;
                this.RaisePropertyChanged("BigOrSmall");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string MiddleOrSide {
            get {
                return this.middleOrSideField;
            }
            set {
                this.middleOrSideField = value;
                this.RaisePropertyChanged("MiddleOrSide");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string OddOrDual {
            get {
                return this.oddOrDualField;
            }
            set {
                this.oddOrDualField = value;
                this.RaisePropertyChanged("OddOrDual");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string MantissaBigOrSmall {
            get {
                return this.mantissaBigOrSmallField;
            }
            set {
                this.mantissaBigOrSmallField = value;
                this.RaisePropertyChanged("MantissaBigOrSmall");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ThreeRemainder {
            get {
                return this.threeRemainderField;
            }
            set {
                this.threeRemainderField = value;
                this.RaisePropertyChanged("ThreeRemainder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string FourRemainder {
            get {
                return this.fourRemainderField;
            }
            set {
                this.fourRemainderField = value;
                this.RaisePropertyChanged("FourRemainder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string FiveRemainder {
            get {
                return this.fiveRemainderField;
            }
            set {
                this.fiveRemainderField = value;
                this.RaisePropertyChanged("FiveRemainder");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LotteryExtByBJ))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LotteryForBJ : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int periodNumField;
        
        private System.DateTime retTimeField;
        
        private int siteSysNoField;
        
        private int retOddNumField;
        
        private int retNumField;
        
        private string retMidNumField;
        
        private string collectRetField;
        
        private System.DateTime collectTimeField;
        
        private int statusField;
        
        private LotteryType typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int PeriodNum {
            get {
                return this.periodNumField;
            }
            set {
                this.periodNumField = value;
                this.RaisePropertyChanged("PeriodNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime RetTime {
            get {
                return this.retTimeField;
            }
            set {
                this.retTimeField = value;
                this.RaisePropertyChanged("RetTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int SiteSysNo {
            get {
                return this.siteSysNoField;
            }
            set {
                this.siteSysNoField = value;
                this.RaisePropertyChanged("SiteSysNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int RetOddNum {
            get {
                return this.retOddNumField;
            }
            set {
                this.retOddNumField = value;
                this.RaisePropertyChanged("RetOddNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int RetNum {
            get {
                return this.retNumField;
            }
            set {
                this.retNumField = value;
                this.RaisePropertyChanged("RetNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string RetMidNum {
            get {
                return this.retMidNumField;
            }
            set {
                this.retMidNumField = value;
                this.RaisePropertyChanged("RetMidNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string CollectRet {
            get {
                return this.collectRetField;
            }
            set {
                this.collectRetField = value;
                this.RaisePropertyChanged("CollectRet");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public System.DateTime CollectTime {
            get {
                return this.collectTimeField;
            }
            set {
                this.collectTimeField = value;
                this.RaisePropertyChanged("CollectTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public LotteryType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LotteryTimes : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private int totalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
                this.RaisePropertyChanged("Total");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LotteryTrend : object, System.ComponentModel.INotifyPropertyChanged {
        
        private LotteryTimes[] lotteryTimesesField;
        
        private PageListOfLotteryExtByBJ pageListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public LotteryTimes[] LotteryTimeses {
            get {
                return this.lotteryTimesesField;
            }
            set {
                this.lotteryTimesesField = value;
                this.RaisePropertyChanged("LotteryTimeses");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public PageListOfLotteryExtByBJ PageList {
            get {
                return this.pageListField;
            }
            set {
                this.pageListField = value;
                this.RaisePropertyChanged("PageList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class User : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int sysNoField;
        
        private string userIDField;
        
        private string userPwdField;
        
        private string userNameField;
        
        private int statusField;
        
        private string regIPField;
        
        private System.DateTime regDateField;
        
        private System.DateTime rechargeUseBeginTimeField;
        
        private System.DateTime rechargeUseEndTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int SysNo {
            get {
                return this.sysNoField;
            }
            set {
                this.sysNoField = value;
                this.RaisePropertyChanged("SysNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
                this.RaisePropertyChanged("UserID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string UserPwd {
            get {
                return this.userPwdField;
            }
            set {
                this.userPwdField = value;
                this.RaisePropertyChanged("UserPwd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string RegIP {
            get {
                return this.regIPField;
            }
            set {
                this.regIPField = value;
                this.RaisePropertyChanged("RegIP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.DateTime RegDate {
            get {
                return this.regDateField;
            }
            set {
                this.regDateField = value;
                this.RaisePropertyChanged("RegDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public System.DateTime RechargeUseBeginTime {
            get {
                return this.rechargeUseBeginTimeField;
            }
            set {
                this.rechargeUseBeginTimeField = value;
                this.RaisePropertyChanged("RechargeUseBeginTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public System.DateTime RechargeUseEndTime {
            get {
                return this.rechargeUseEndTimeField;
            }
            set {
                this.rechargeUseEndTimeField = value;
                this.RaisePropertyChanged("RechargeUseEndTime");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PageListOfLotteryForBJ : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int totalField;
        
        private LotteryForBJ[] listField;
        
        private int pageSizeField;
        
        private int pageIndexField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
                this.RaisePropertyChanged("Total");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public LotteryForBJ[] List {
            get {
                return this.listField;
            }
            set {
                this.listField = value;
                this.RaisePropertyChanged("List");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int PageSize {
            get {
                return this.pageSizeField;
            }
            set {
                this.pageSizeField = value;
                this.RaisePropertyChanged("PageSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int PageIndex {
            get {
                return this.pageIndexField;
            }
            set {
                this.pageIndexField = value;
                this.RaisePropertyChanged("PageIndex");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ResultRMOfPageListOfLotteryForBJ : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool successField;
        
        private string messageField;
        
        private PageListOfLotteryForBJ dataField;
        
        private int codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("Success");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public PageListOfLotteryForBJ Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("Data");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LotteryFilterForBJ : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int pageIndexField;
        
        private int pageSizeField;
        
        private System.Nullable<System.DateTime> fromField;
        
        private System.Nullable<System.DateTime> toField;
        
        private string siteNameField;
        
        private string gameNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int PageIndex {
            get {
                return this.pageIndexField;
            }
            set {
                this.pageIndexField = value;
                this.RaisePropertyChanged("PageIndex");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int PageSize {
            get {
                return this.pageSizeField;
            }
            set {
                this.pageSizeField = value;
                this.RaisePropertyChanged("PageSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<System.DateTime> From {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
                this.RaisePropertyChanged("From");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<System.DateTime> To {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
                this.RaisePropertyChanged("To");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string SiteName {
            get {
                return this.siteNameField;
            }
            set {
                this.siteNameField = value;
                this.RaisePropertyChanged("SiteName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string GameName {
            get {
                return this.gameNameField;
            }
            set {
                this.gameNameField = value;
                this.RaisePropertyChanged("GameName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ResultRMOfLotteryForBJ : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool successField;
        
        private string messageField;
        
        private LotteryForBJ dataField;
        
        private int codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("Success");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public LotteryForBJ Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("Data");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CustomModules : object, System.ComponentModel.INotifyPropertyChanged {
        
        private LotteryByTwentyPeriod m1Field;
        
        private LotteryByTwentyPeriod m2Field;
        
        private LotteryByTwentyPeriod m3Field;
        
        private LotteryByTwentyPeriod m4Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public LotteryByTwentyPeriod M1 {
            get {
                return this.m1Field;
            }
            set {
                this.m1Field = value;
                this.RaisePropertyChanged("M1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public LotteryByTwentyPeriod M2 {
            get {
                return this.m2Field;
            }
            set {
                this.m2Field = value;
                this.RaisePropertyChanged("M2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public LotteryByTwentyPeriod M3 {
            get {
                return this.m3Field;
            }
            set {
                this.m3Field = value;
                this.RaisePropertyChanged("M3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public LotteryByTwentyPeriod M4 {
            get {
                return this.m4Field;
            }
            set {
                this.m4Field = value;
                this.RaisePropertyChanged("M4");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LotteryByTwentyPeriod : object, System.ComponentModel.INotifyPropertyChanged {
        
        private LotteryForBJ[] lotteriesField;
        
        private int[] notAppearNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public LotteryForBJ[] Lotteries {
            get {
                return this.lotteriesField;
            }
            set {
                this.lotteriesField = value;
                this.RaisePropertyChanged("Lotteries");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public int[] NotAppearNumber {
            get {
                return this.notAppearNumberField;
            }
            set {
                this.notAppearNumberField = value;
                this.RaisePropertyChanged("NotAppearNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ResultRMOfCustomModules : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool successField;
        
        private string messageField;
        
        private CustomModules dataField;
        
        private int codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("Success");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public CustomModules Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("Data");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ResultRMOfLotteryByTwentyPeriod : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool successField;
        
        private string messageField;
        
        private LotteryByTwentyPeriod dataField;
        
        private int codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("Success");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public LotteryByTwentyPeriod Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("Data");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryNextLotteryWithSameNumber", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class QueryNextLotteryWithSameNumberRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public UnitTest.LotteryWebService.TokenHeader TokenHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int number;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string siteName;
        
        public QueryNextLotteryWithSameNumberRequest() {
        }
        
        public QueryNextLotteryWithSameNumberRequest(UnitTest.LotteryWebService.TokenHeader TokenHeader, int number, string siteName) {
            this.TokenHeader = TokenHeader;
            this.number = number;
            this.siteName = siteName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryNextLotteryWithSameNumberResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class QueryNextLotteryWithSameNumberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public UnitTest.LotteryWebService.ResultRMOfLotteryByTwentyPeriod QueryNextLotteryWithSameNumberResult;
        
        public QueryNextLotteryWithSameNumberResponse() {
        }
        
        public QueryNextLotteryWithSameNumberResponse(UnitTest.LotteryWebService.ResultRMOfLotteryByTwentyPeriod QueryNextLotteryWithSameNumberResult) {
            this.QueryNextLotteryWithSameNumberResult = QueryNextLotteryWithSameNumberResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryLotteryByHourStep", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class QueryLotteryByHourStepRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public UnitTest.LotteryWebService.TokenHeader TokenHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.DateTime time;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string siteName;
        
        public QueryLotteryByHourStepRequest() {
        }
        
        public QueryLotteryByHourStepRequest(UnitTest.LotteryWebService.TokenHeader TokenHeader, System.DateTime time, string siteName) {
            this.TokenHeader = TokenHeader;
            this.time = time;
            this.siteName = siteName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryLotteryByHourStepResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class QueryLotteryByHourStepResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public UnitTest.LotteryWebService.ResultRMOfLotteryByTwentyPeriod QueryLotteryByHourStepResult;
        
        public QueryLotteryByHourStepResponse() {
        }
        
        public QueryLotteryByHourStepResponse(UnitTest.LotteryWebService.ResultRMOfLotteryByTwentyPeriod QueryLotteryByHourStepResult) {
            this.QueryLotteryByHourStepResult = QueryLotteryByHourStepResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryLotteryByDay", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class QueryLotteryByDayRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public UnitTest.LotteryWebService.TokenHeader TokenHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.DateTime time;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string siteName;
        
        public QueryLotteryByDayRequest() {
        }
        
        public QueryLotteryByDayRequest(UnitTest.LotteryWebService.TokenHeader TokenHeader, System.DateTime time, string siteName) {
            this.TokenHeader = TokenHeader;
            this.time = time;
            this.siteName = siteName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryLotteryByDayResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class QueryLotteryByDayResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public UnitTest.LotteryWebService.ResultRMOfLotteryByTwentyPeriod QueryLotteryByDayResult;
        
        public QueryLotteryByDayResponse() {
        }
        
        public QueryLotteryByDayResponse(UnitTest.LotteryWebService.ResultRMOfLotteryByTwentyPeriod QueryLotteryByDayResult) {
            this.QueryLotteryByDayResult = QueryLotteryByDayResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCustomeModule", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCustomeModuleRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public UnitTest.LotteryWebService.TokenHeader TokenHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string siteName;
        
        public GetCustomeModuleRequest() {
        }
        
        public GetCustomeModuleRequest(UnitTest.LotteryWebService.TokenHeader TokenHeader, string siteName) {
            this.TokenHeader = TokenHeader;
            this.siteName = siteName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCustomeModuleResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCustomeModuleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public UnitTest.LotteryWebService.ResultRMOfCustomModules GetCustomeModuleResult;
        
        public GetCustomeModuleResponse() {
        }
        
        public GetCustomeModuleResponse(UnitTest.LotteryWebService.ResultRMOfCustomModules GetCustomeModuleResult) {
            this.GetCustomeModuleResult = GetCustomeModuleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryLotteryByTwenty", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class QueryLotteryByTwentyRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public UnitTest.LotteryWebService.TokenHeader TokenHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string siteName;
        
        public QueryLotteryByTwentyRequest() {
        }
        
        public QueryLotteryByTwentyRequest(UnitTest.LotteryWebService.TokenHeader TokenHeader, string siteName) {
            this.TokenHeader = TokenHeader;
            this.siteName = siteName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryLotteryByTwentyResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class QueryLotteryByTwentyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public UnitTest.LotteryWebService.ResultRMOfLotteryByTwentyPeriod QueryLotteryByTwentyResult;
        
        public QueryLotteryByTwentyResponse() {
        }
        
        public QueryLotteryByTwentyResponse(UnitTest.LotteryWebService.ResultRMOfLotteryByTwentyPeriod QueryLotteryByTwentyResult) {
            this.QueryLotteryByTwentyResult = QueryLotteryByTwentyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryCurrentLottery", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class QueryCurrentLotteryRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public UnitTest.LotteryWebService.TokenHeader TokenHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string siteName;
        
        public QueryCurrentLotteryRequest() {
        }
        
        public QueryCurrentLotteryRequest(UnitTest.LotteryWebService.TokenHeader TokenHeader, string siteName) {
            this.TokenHeader = TokenHeader;
            this.siteName = siteName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryCurrentLotteryResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class QueryCurrentLotteryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public UnitTest.LotteryWebService.ResultRMOfLotteryForBJ QueryCurrentLotteryResult;
        
        public QueryCurrentLotteryResponse() {
        }
        
        public QueryCurrentLotteryResponse(UnitTest.LotteryWebService.ResultRMOfLotteryForBJ QueryCurrentLotteryResult) {
            this.QueryCurrentLotteryResult = QueryCurrentLotteryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Query", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class QueryRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public UnitTest.LotteryWebService.TokenHeader TokenHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public UnitTest.LotteryWebService.LotteryFilterForBJ filterForBj;
        
        public QueryRequest() {
        }
        
        public QueryRequest(UnitTest.LotteryWebService.TokenHeader TokenHeader, UnitTest.LotteryWebService.LotteryFilterForBJ filterForBj) {
            this.TokenHeader = TokenHeader;
            this.filterForBj = filterForBj;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class QueryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public UnitTest.LotteryWebService.ResultRMOfPageListOfLotteryForBJ QueryResult;
        
        public QueryResponse() {
        }
        
        public QueryResponse(UnitTest.LotteryWebService.ResultRMOfPageListOfLotteryForBJ QueryResult) {
            this.QueryResult = QueryResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LotteryWebServiceSoapChannel : UnitTest.LotteryWebService.LotteryWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LotteryWebServiceSoapClient : System.ServiceModel.ClientBase<UnitTest.LotteryWebService.LotteryWebServiceSoap>, UnitTest.LotteryWebService.LotteryWebServiceSoap {
        
        public LotteryWebServiceSoapClient() {
        }
        
        public LotteryWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LotteryWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LotteryWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LotteryWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UnitTest.LotteryWebService.QueryNextLotteryWithSameNumberResponse UnitTest.LotteryWebService.LotteryWebServiceSoap.QueryNextLotteryWithSameNumber(UnitTest.LotteryWebService.QueryNextLotteryWithSameNumberRequest request) {
            return base.Channel.QueryNextLotteryWithSameNumber(request);
        }
        
        public UnitTest.LotteryWebService.ResultRMOfLotteryByTwentyPeriod QueryNextLotteryWithSameNumber(UnitTest.LotteryWebService.TokenHeader TokenHeader, int number, string siteName) {
            UnitTest.LotteryWebService.QueryNextLotteryWithSameNumberRequest inValue = new UnitTest.LotteryWebService.QueryNextLotteryWithSameNumberRequest();
            inValue.TokenHeader = TokenHeader;
            inValue.number = number;
            inValue.siteName = siteName;
            UnitTest.LotteryWebService.QueryNextLotteryWithSameNumberResponse retVal = ((UnitTest.LotteryWebService.LotteryWebServiceSoap)(this)).QueryNextLotteryWithSameNumber(inValue);
            return retVal.QueryNextLotteryWithSameNumberResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UnitTest.LotteryWebService.QueryLotteryByHourStepResponse UnitTest.LotteryWebService.LotteryWebServiceSoap.QueryLotteryByHourStep(UnitTest.LotteryWebService.QueryLotteryByHourStepRequest request) {
            return base.Channel.QueryLotteryByHourStep(request);
        }
        
        public UnitTest.LotteryWebService.ResultRMOfLotteryByTwentyPeriod QueryLotteryByHourStep(UnitTest.LotteryWebService.TokenHeader TokenHeader, System.DateTime time, string siteName) {
            UnitTest.LotteryWebService.QueryLotteryByHourStepRequest inValue = new UnitTest.LotteryWebService.QueryLotteryByHourStepRequest();
            inValue.TokenHeader = TokenHeader;
            inValue.time = time;
            inValue.siteName = siteName;
            UnitTest.LotteryWebService.QueryLotteryByHourStepResponse retVal = ((UnitTest.LotteryWebService.LotteryWebServiceSoap)(this)).QueryLotteryByHourStep(inValue);
            return retVal.QueryLotteryByHourStepResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UnitTest.LotteryWebService.QueryLotteryByDayResponse UnitTest.LotteryWebService.LotteryWebServiceSoap.QueryLotteryByDay(UnitTest.LotteryWebService.QueryLotteryByDayRequest request) {
            return base.Channel.QueryLotteryByDay(request);
        }
        
        public UnitTest.LotteryWebService.ResultRMOfLotteryByTwentyPeriod QueryLotteryByDay(UnitTest.LotteryWebService.TokenHeader TokenHeader, System.DateTime time, string siteName) {
            UnitTest.LotteryWebService.QueryLotteryByDayRequest inValue = new UnitTest.LotteryWebService.QueryLotteryByDayRequest();
            inValue.TokenHeader = TokenHeader;
            inValue.time = time;
            inValue.siteName = siteName;
            UnitTest.LotteryWebService.QueryLotteryByDayResponse retVal = ((UnitTest.LotteryWebService.LotteryWebServiceSoap)(this)).QueryLotteryByDay(inValue);
            return retVal.QueryLotteryByDayResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UnitTest.LotteryWebService.GetCustomeModuleResponse UnitTest.LotteryWebService.LotteryWebServiceSoap.GetCustomeModule(UnitTest.LotteryWebService.GetCustomeModuleRequest request) {
            return base.Channel.GetCustomeModule(request);
        }
        
        public UnitTest.LotteryWebService.ResultRMOfCustomModules GetCustomeModule(UnitTest.LotteryWebService.TokenHeader TokenHeader, string siteName) {
            UnitTest.LotteryWebService.GetCustomeModuleRequest inValue = new UnitTest.LotteryWebService.GetCustomeModuleRequest();
            inValue.TokenHeader = TokenHeader;
            inValue.siteName = siteName;
            UnitTest.LotteryWebService.GetCustomeModuleResponse retVal = ((UnitTest.LotteryWebService.LotteryWebServiceSoap)(this)).GetCustomeModule(inValue);
            return retVal.GetCustomeModuleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UnitTest.LotteryWebService.QueryLotteryByTwentyResponse UnitTest.LotteryWebService.LotteryWebServiceSoap.QueryLotteryByTwenty(UnitTest.LotteryWebService.QueryLotteryByTwentyRequest request) {
            return base.Channel.QueryLotteryByTwenty(request);
        }
        
        public UnitTest.LotteryWebService.ResultRMOfLotteryByTwentyPeriod QueryLotteryByTwenty(UnitTest.LotteryWebService.TokenHeader TokenHeader, string siteName) {
            UnitTest.LotteryWebService.QueryLotteryByTwentyRequest inValue = new UnitTest.LotteryWebService.QueryLotteryByTwentyRequest();
            inValue.TokenHeader = TokenHeader;
            inValue.siteName = siteName;
            UnitTest.LotteryWebService.QueryLotteryByTwentyResponse retVal = ((UnitTest.LotteryWebService.LotteryWebServiceSoap)(this)).QueryLotteryByTwenty(inValue);
            return retVal.QueryLotteryByTwentyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UnitTest.LotteryWebService.QueryCurrentLotteryResponse UnitTest.LotteryWebService.LotteryWebServiceSoap.QueryCurrentLottery(UnitTest.LotteryWebService.QueryCurrentLotteryRequest request) {
            return base.Channel.QueryCurrentLottery(request);
        }
        
        public UnitTest.LotteryWebService.ResultRMOfLotteryForBJ QueryCurrentLottery(UnitTest.LotteryWebService.TokenHeader TokenHeader, string siteName) {
            UnitTest.LotteryWebService.QueryCurrentLotteryRequest inValue = new UnitTest.LotteryWebService.QueryCurrentLotteryRequest();
            inValue.TokenHeader = TokenHeader;
            inValue.siteName = siteName;
            UnitTest.LotteryWebService.QueryCurrentLotteryResponse retVal = ((UnitTest.LotteryWebService.LotteryWebServiceSoap)(this)).QueryCurrentLottery(inValue);
            return retVal.QueryCurrentLotteryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UnitTest.LotteryWebService.QueryResponse UnitTest.LotteryWebService.LotteryWebServiceSoap.Query(UnitTest.LotteryWebService.QueryRequest request) {
            return base.Channel.Query(request);
        }
        
        public UnitTest.LotteryWebService.ResultRMOfPageListOfLotteryForBJ Query(UnitTest.LotteryWebService.TokenHeader TokenHeader, UnitTest.LotteryWebService.LotteryFilterForBJ filterForBj) {
            UnitTest.LotteryWebService.QueryRequest inValue = new UnitTest.LotteryWebService.QueryRequest();
            inValue.TokenHeader = TokenHeader;
            inValue.filterForBj = filterForBj;
            UnitTest.LotteryWebService.QueryResponse retVal = ((UnitTest.LotteryWebService.LotteryWebServiceSoap)(this)).Query(inValue);
            return retVal.QueryResult;
        }
        
        public string Login(string userName, string psw) {
            return base.Channel.Login(userName, psw);
        }
        
        public int Register(UnitTest.LotteryWebService.User user) {
            return base.Channel.Register(user);
        }
        
        public string GenerateCode() {
            return base.Channel.GenerateCode();
        }
        
        public UnitTest.LotteryWebService.LotteryTrend QueryTrend(System.DateTime from, System.DateTime to, int pageSize, int pageIndex) {
            return base.Channel.QueryTrend(from, to, pageSize, pageIndex);
        }
    }
}
